name: API Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test

      - uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: build/reports

      - name: Show report files
        run: ls -R build/reports

      - name: Upload Cucumber Reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-api-reports
          path: build/reports