name: Run Web UI Automation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-web-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run tests with Chrome Headless
        run: |
          export CHROME_BIN=$(which chrome)
          ./gradlew test -Dwebdriver.chrome.driver=chrome